# Generated by Django 4.1 on 2022-09-08 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('developer', 'developer'), ('guest', 'guest'), ('empoloyee', 'empoloyee')], default='developer', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam 9981234567 formatida bo'lishi kerak", regex='^998\\d{9}$')]),
        ),
    ]
