# Generated by Django 4.1 on 2022-09-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_telegram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
