# Generated by Django 4.0.3 on 2022-08-05 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_social_github'),
        ('projects', '0013_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
